webshop/cart/urls.py
from django.urls import path

from cart.views import cart_detail, cart_add, cart_remove

app_name = 'cart'
urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),

]

webshop/coupons/urls.py
from django.urls import path

from coupons.views import coupon_apply

app_name = 'couponse'
urlpatterns = [
    path('apply/', coupon_apply, name='apply'),

]

webshop/orders/urls.py
from django.urls import path

from orders.views import order_create

app_name = 'orders'
urlpatterns = [
    path('', order_create, name='order_create'),

]

webshop/shop/urls.py
from django.contrib import admin
from django.urls import path

from shop.views import product_list, product_detail

app_name = 'shop'
urlpatterns = [
    path('', product_list, name='product_list'),
    path('<slug:category_slug>/', product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', product_detail, name='product_detail'),

]

webshop/webshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('create/', include('orders.urls', namespace='orders')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('shop.urls', namespace='shop')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webshop/cart/models.py
from django.db import models

# Create your models here.

webshop/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,
                                      coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

webshop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from cart.cart import Cart
from cart.forms import CartAddProductForm
from coupons.forms import CouponApplyForm
from shop.models import Product


@require_POST
def cart_add(request, product_id):
    """Дабавить в корзину"""
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    """Удалить из корзины"""
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    """Список товаров добавленных в корзину"""
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'update': True})
    coupon_apply_form = CouponApplyForm()
    return render(request, 'cart/detail.html', {'cart': cart,
                                                'coupon_apply_form': coupon_apply_form})

webshop/cart/templates/cart/detail.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}Ваша корзина покупок{% endblock %}
{% block content %}
    <h1>Ваша корзина покупок</h1>
    <table class="cart">
        <thead>
            <tr>
                <th>Изображение</th>
                <th>Товар</th>
                <th>Количество</th>
                <th>Удалить</th>
                <th>Цена единицы товара</th>
                <th>Общая цена</th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart %}
                {% with product=item.product %}
                    <tr>
                        <td>
                            <a href="{{ product.get_absolute_url }}">
                                <img src="{% if product.image %}{{ product.image.url }}
                                {% else %}{% static 'img/no_image.png' %}{% endif %}">
                            </a>
                        </td>
                        <td>{{ product.name }}</td>
                        <td>
                            <form action="{% url 'cart:cart_add' product.id %}" method="POST">
                                {{ item.update_quantity_form.quantity }}
                                {{ item.update_quantity_form.update }}
                                {% csrf_token %}
                                <input type="submit" value="Изменить">
                            </form>
                        </td>
                        <td><a href="{% url 'cart:cart_remove' product.id %}">Удалить</a></td>
                        <td>{{ item.price }}</td>
                        <td>{{ item.total_price }}</td>
                    </tr>
                {% endwith %}
            {% endfor %}
            {% if cart.coupon %}
                <tr class="subtotal">
                    <td>Общая сумма без скидки</td>
                    <td colspan="4"></td>
                    <td class="num">{{ cart.get_total_price | floatformat:"2" }}</td>
                </tr>
                <tr>
                    <td>
                        Код купона: "{{ cart.coupon.code }}"
                        ({{ cart.coupon.discount }}%)
                    </td>
                    <td colspan="4"></td>
                    <td class="num neg">
                        {{ cart.get_discount | floatformat:"2" }}
                    </td>
                </tr>
            {% endif %}
            <tr class="total">
                <td>Сумма к оплате</td>
                <td colspan="4"></td>
                <td class="num">
                    {{ cart.get_total_price_after_discount | floatformat:"2" }}
                </td>
            </tr>
        </tbody>
    </table>
    <p>Применить купон</p>
    <form action="{% url 'coupons:apply' %}" method="POST">
        {{ coupon_apply_form }}
        <input type="submit" value="Применить">
        {% csrf_token %}
    </form>
    <p class="text-right">
        <a href="{% url 'shop:product_list' %}" class="button light">Продолжить покупки</a>
        <a href="{% url 'orders:order_create' %}" class="button">Выбрать</a>
    </p>
{% endblock %}